### ISSUE TITLE
Vague error message is shown regardless of gdb error message

### ISSUE THREAD

**Issue by digittigerw** [Microsoft/MIEngine#639] opened 2017-07-05 21:51 UTC
When we step into a function that has no debug info  nor symbol table data,  GDB will fail to get call stack, and performing step-out will result in such error:
  ""finish" not meaningful in the outermost frame."
That is fine.

But when we do that in Visual Studio, a UnexpectedMIResultException will be thrown from MIEngine to core debugger which will throw up a dialog with such message:
   "Unable to step.  The message is improperly formatted or was damaged in transit."
That message is so vague that it does not help user at all.

I think it better (though not perfect) if the dialog can show message like
    ""finish" not meaningful in the outermost frame."

My investigation shows that the "Message" property of  UnexpectedMIResultException is not accessed by core debugger, but core debugger is a black box to me.  

So it there a way to fix that ?

**Comment by pieandcakes** [comment] 2017-07-05 23:53
@digittigerw I fixed this in https://github.com/Microsoft/MIEngine/commit/b0baa033d14c35e3a44a4829911f86f4724d8014. The problem is that the exception was not caught and passed back as a message. This will be fixed in Visual Studio 2017 Update 3.

**Comment by digittigerw** [comment] 2017-07-06 15:02
@pieandcakes Great ! Do you mean some change is also made in VS core debugger aside from change in MIEngine ?

**Comment by pieandcakes** [comment] 2017-07-06 20:41
@digittigerw The change is not necessary in the core debugger. This changes fixes it so that we don't let the exception flow to VS (which is then caught and given as a generic error) and instead returns from the AD7 request as a failure with a message which is then shown to the user.

**Comment by digittigerw** [comment] 2017-07-07 23:06
I actually tried your change to AD7Engine and it did work for me.  I asked because you mentioned "this will be fixed in VS 2017 update 3" :)  Anyway, it works. Thanks !

**Comment by pieandcakes** [comment] 2017-07-07 23:08
@digittigerw I mentioned that because you said:
>But when we do that in Visual Studio, a UnexpectedMIResultException will be thrown from MIEngine to core debugger which will throw up a dialog with such message:

Which made me assume you are using it in Visual Studio as part of what we ship today in VS. If you are building and using it from this repo directly then you should be good to go.

**Closed by pieandcakes** 2017-07-07 23:08 UTC
Labels: bug, Resolved-Fixed
