### ISSUE TITLE
Multiple source files with the same name can cause breakpoint isues.

### ISSUE THREAD

**Issue by chuckries** [microsoft/MIEngine#147] opened 2016-01-05 21:58 UTC
From VS Feedback item:

1) Make two shared objects by having 2 projects in a Solution
    (Denote these by project/library 'A' and 'B')
2) In two separate projects, create a C++ source file in each with the same name 
    (in my solution/workflow, "OnLoad.cpp" appears in multiple projects (which are made into multiple .so files)
3) Put a breakpoint in one of the "OnLoad.cpp" files 
    (in my case, I put a breakpoint in the last library loaded by my application)
    (App loads project 'A' and then project 'B' libraries -- which means my breakpoint was in project 'B')
4) Start Debugging using GDB. If the breakpoint is in said file contained in project 'B', the debugger interprets project 'A's file with the same name and will use the breakpoints in project 'A's library -- not project 'B' as you desired.

**Comment by erwanh1112** [comment] 2016-12-22 13:06
Here are somewhat simplified repro steps on VS2015 U3 + KB3165756 (version 14.0. 25431.01)

1. Create a new solution and project Console Application (Linux) named A
2. Add to the solution a new project  Console Application (Linux) named B
3. In the Solution Explorer, right-click on the solution and select Project Dependencies... Add a dependency on project A to project B, such that B builds first
4. Ensure that A is the active project
5. _In project B_, Set a breakpoint (F9) on main.cpp@6 -- i.e. on the printf() line
6. Press F5. Enter the information to connect to the remote Linux box

The debugger breaks on A.exe!main.cpp@6. The debugger should not break at all since the breakpoint is actually set on project B, which is not part of the debug session. In Visual Studio, when debugging starts, the breakpoint visually moves from B.exe!main.cpp@6 to A.exe!main.cpp@6 . When debugging stops, the breakpoint moves back to B.exe!main.cpp@6

When looking at the debug output in VS, we can see the following:

-file-exec-and-symbols .../bin/x64/Debug/A.exe
-break-insert main
-break-insert -f main.cpp:6
-symbol-list-lines main.cpp
-exec-run

It appears that the MIEngine notifies GDB to set a breakpoint on the executable being debugged (i.e. A.exe) on main.cpp@6, event though the breakpoint is actually set on a different project B. Note that the issue reproduces with either GDB or GDBSERVER

**Comment by gregg-miskelly** [comment] 2016-12-22 14:29
@erwanh1112 the MIEngine has logic to try and pick the better match if it sees the same breakpoint bound to two different locations. But if a breakpoint only binds to one spot, this is what you are going to get.

**Comment by erwanh1112** [comment] 2016-12-22 16:21
@gregg-miskelly Thank you for your prompt feedback! It looks like the MIEngine does not discriminate between source files with the same name but in different directories -- in my case between $(SolutionDir)\A\main.cpp and $(SolutionDir)\B\main.cpp. As a result a breakpoint set on B\main.cpp "moves" to A\main.cpp when debugging starts.

Are you saying that this behavior is by design and cannot be changed? Short of preventing files in the same solution but in different projects from having the same name, can you think of a workaround to this issue?

________________________________

**Comment by gregg-miskelly** [comment] 2016-12-22 17:22
@erwanh1112 unfortunately because gdb/lldb/clang/gcc don't support source file checksums (which is the best way to deal with this problem) MIEngine can't have a great solution to this problem. If we passed the full path to the source file then GDB wouldn't bind in the case that the Visual Studio view of the code is different from when the compiler saw the code (ex: cross machine scenarios, build lab scenarios, etc). But it can do better --

1. Extra options: MIEngine should support some sort of 'sourceMap' launch option (and maybe tools->Options also?) to teach MIEngine that when I see a breakpoint in c:\bar\foo.cpp, I should set the breakpoint in /home/greggm/bar/foo.cpp, and also that breakpoints in c:\jam can be safely set in the same source location.
2. Multiple bind resolution: I thought MIEngine already had support for handling the disambiguation in the case that all the modules containing 'foo.cpp' were loaded at the same time by automatically trying to choose the best match. But if so, I can't seem to find it. So it should have that also.

One note: if you are using Visual Studio, you may be able to manually work around this today by going to the breakpoints window, expand the tree of breakpoints, and unchecking the bound breakpoint that you don't want. This assumes that the breakpoint is immediately binding to multiple locations and that we are able to get enough information from GDB to actually display them all.

**Comment by WardenGnaw** [comment] 2022-03-10 20:41
Resolved in https://github.com/microsoft/MIEngine/pull/541

**Closed by WardenGnaw** 2022-03-10 20:41 UTC
