### ISSUE TITLE
Unable to start debugging. Cannot access a disposed object. Object name: 'Debugger'

### ISSUE THREAD

**Issue by weidazhao** [Microsoft/MIEngine#478] opened 2016-10-20 17:11 UTC
Debugging stops working on one of my machines. VS keeps saying "Unable to start debugging. Cannot access a disposed object. Object name: 'Debugger'".

Below are the version info and logs collected from two machines, one that works, the other that stops working:

The one that works:

```
    --a-- W32i   DLL   -    14.0.31017.1 shp    189,632 10-17-2016 microsoft.micore.dll
    Language        0x0000 (Language Neutral)
    CharSet         0x04b0 Unicode
    OleSelfRegister Disabled
    CompanyName     Microsoft Corporation
    FileDescription Microsoft.MICore
    InternalName    Microsoft.MICore.dll
    OriginalFilenam Microsoft.MICore.dll
    ProductName     Microsoft « Visual Studio «
    ProductVersion  14.0.31017.1 commit:0a0257f91a7b47ab7aa5d4c6e84e2975c7e7188d
    FileVersion     14.0.31017.1
    LegalCopyright  ⌐ Microsoft Corporation. All rights reserved.
    Comments
    OleSelfRegister Disabled

    VS_FIXEDFILEINFO:
    Signature:      feef04bd
    Struc Ver:      00010000
    FileVer:        000e0000:79290001 (14.0:31017.1)
    ProdVer:        000e0000:79290001 (14.0:31017.1)
    FlagMask:       0000003f
    Flags:          00000000
    OS:             00000004 Win32
    FileType:       00000002 Dll
    SubType:        00000000
    FileDate:       00000000:00000000
```

[Microsoft.MIDebug.succeed.log.txt](https://github.com/Microsoft/MIEngine/files/542348/Microsoft.MIDebug.succeed.log.txt)

The one that doesn't work:

```
    --a-- W32i   DLL   -    14.0.30502.0 shp    152,264 05-02-2016 microsoft.micore.dll
    Language        0x0000 (Language Neutral)
    CharSet         0x04b0 Unicode
    OleSelfRegister Disabled
    CompanyName     Microsoft Corporation
    FileDescription Microsoft.MICore
    InternalName    Microsoft.MICore.dll
    OriginalFilenam Microsoft.MICore.dll
    ProductName     Microsoft « Visual Studio «
    ProductVersion  14.0.30502.0 commit:5ef401477e2f31bd348e71f9e469aa0a7d4e7920
    FileVersion     14.0.30502.0
    LegalCopyright  ⌐ Microsoft Corporation. All rights reserved.
    Comments
    OleSelfRegister Disabled

    VS_FIXEDFILEINFO:
    Signature:      feef04bd
    Struc Ver:      00010000
    FileVer:        000e0000:77260000 (14.0:30502.0)
    ProdVer:        00000000:00000000 (0.0:0.0)
    FlagMask:       0000003f
    Flags:          00000000
    OS:             00000004 Win32
    FileType:       00000002 Dll
    SubType:        00000000
    FileDate:       00000000:00000000
```

[Microsoft.MIDebug.fail.log.txt](https://github.com/Microsoft/MIEngine/files/542347/Microsoft.MIDebug.fail.log.txt)

**Comment by gregg-miskelly** [comment] 2016-10-20 17:26
This doesn't sound like a bug in the MIEngine (other than that maybe the error message should be better). Either clrdbg crashed in the container or the docker transport is failing.

**Comment by chunseoklee** [comment] 2016-10-20 19:45
If you see the msg on experimental instance, For me, resetting experimental instance and cleaning registry of exp instance resolve the issue.

**Comment by gregg-miskelly** [comment] 2016-10-24 18:11
The cause of this turned out be a problem with Docker -- Docker is closing stdin inside the container, leading clrdbg to exit.

Leaving this bug open since we might want to think about improving the error message here.

**Comment by gregg-miskelly** [comment] 2016-11-18 00:38
Error message is improved with https://github.com/Microsoft/MIEngine/pull/500

**Closed by gregg-miskelly** 2016-11-18 00:38 UTC
